"""
snaked_map_builder.py

A simple grid for the game "Snaked".

Conventions
-----------
- 1 Blender unit == 1 tile.
- X and Y are the grid directions.
- Z is height.
- Everything generated by this script is placed under a single
  collection ("Snaked_Map") so it can be wiped and rebuilt cleanly.

Run this from Blender's Text Editor (Alt+P) or via the command line:
    blender --python snaked_map_builder.py
"""

import bpy
import math

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

COLLECTION_NAME = "Snaked_Map"
GRID_WIDTH = 22   # tiles along X
GRID_HEIGHT = 40  # tiles along Y

# Layers stacked along Z. Layer 0 is the floor; layers 1..3 hold obstacles.
NUM_LAYERS = 4       # 1 floor + 3 obstacle layers
LAYER_HEIGHT = 1.0   # Z distance between layers (1 unit == 1 tile)


# ---------------------------------------------------------------------------
# Material helpers
# ---------------------------------------------------------------------------

def _get_material(name, color):
    """Return a material with the given name, creating it if needed."""
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = False
    mat.diffuse_color = (color[0], color[1], color[2], 1.0)
    return mat


def _apply_material(obj, name, color):
    mat = _get_material(name, color)
    obj.data.materials.clear()
    obj.data.materials.append(mat)


# ---------------------------------------------------------------------------
# Collection / cleanup helpers
# ---------------------------------------------------------------------------

def get_map_collection():
    """Return the dedicated map collection, creating and linking it if needed."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        coll = bpy.data.collections.new(COLLECTION_NAME)
        bpy.context.scene.collection.children.link(coll)
    return coll


def clear_map():
    """Remove all previously generated objects (and their data) from the map."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        return

    for obj in list(coll.objects):
        mesh = obj.data if obj.type == 'MESH' else None
        bpy.data.objects.remove(obj, do_unlink=True)
        if mesh is not None and mesh.users == 0:
            bpy.data.meshes.remove(mesh)


def _link_to_map(obj):
    """Unlink an object from any other collection and place it in the map collection."""
    coll = get_map_collection()
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    coll.objects.link(obj)


# ---------------------------------------------------------------------------
# Geometry helper
# ---------------------------------------------------------------------------

def _add_box(name, location, size):
    """Create a box (cube) mesh object with explicit per-axis dimensions."""
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=location)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = (size[0], size[1], size[2])
    _link_to_map(obj)
    return obj


# ---------------------------------------------------------------------------
# Visible grid
# ---------------------------------------------------------------------------

def _create_grid_layer(width, height, layer, z):
    """Draw a single flat width x height grid at height z (layer index for naming)."""
    line_thickness = 0.02

    # The floor layer is brighter; obstacle layers are dimmer.
    if layer == 0:
        mat_name, color = "Snaked_GridFloor", (0.35, 0.35, 0.35)
    else:
        mat_name, color = "Snaked_GridLayer", (0.2, 0.2, 0.2)

    # Grid spans from -0.5 to N-0.5 on each axis so every integer tile sits in a cell.
    x_lo, x_hi = 0.5, width + 0.5
    y_lo, y_hi = 0.5, height + 0.5
    x_span = x_hi - x_lo
    y_span = y_hi - y_lo
    x_center = (x_lo + x_hi) / 2.0
    y_center = (y_lo + y_hi) / 2.0

    # Lines parallel to Y (varying X position).
    for i in range(width + 1):
        x = x_lo + i
        obj = _add_box(
            "Grid_L%d_LineY_%02d" % (layer, i),
            location=(x, y_center, z),
            size=(line_thickness, y_span, line_thickness),
        )
        _apply_material(obj, mat_name, color)

    # Lines parallel to X (varying Y position).
    for j in range(height + 1):
        y = y_lo + j
        obj = _add_box(
            "Grid_L%d_LineX_%02d" % (layer, j),
            location=(x_center, y, z),
            size=(x_span, line_thickness, line_thickness),
        )
        _apply_material(obj, mat_name, color)


def create_grid(width=GRID_WIDTH, height=GRID_HEIGHT, num_layers=NUM_LAYERS):
    """Create a stack of width x height grids, one per layer along Z.

    Layer 0 (z=0) is the floor; layers 1..num_layers-1 are obstacle layers
    spaced LAYER_HEIGHT apart. Tiles are centered on integer coordinates
    (0..width-1, 0..height-1) at each layer.
    """
    for layer in range(num_layers):
        z = layer * LAYER_HEIGHT
        _create_grid_layer(width, height, layer, z)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def rebuild():
    """Clear any previous generation and rebuild the grid."""
    clear_map()
    get_map_collection()
    create_grid()
    print("[Snaked] Grid rebuilt: %dx%d x %d layers (1 floor + %d obstacle)." %
          (GRID_WIDTH, GRID_HEIGHT, NUM_LAYERS, NUM_LAYERS - 1))


if __name__ == "__main__":
    rebuild()
