"""
snaked_map_builder.py

A simple grid for the game "Snaked".

Conventions
-----------
- 1 Blender unit == 1 tile.
- X and Y are the grid directions.
- Z is height.
- Everything generated by this script is placed under a single
  collection ("Snaked_Map") so it can be wiped and rebuilt cleanly.

Run this from Blender's Text Editor (Alt+P) or via the command line:
    blender --python snaked_map_builder.py
"""

import bpy
import math

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

COLLECTION_NAME = "Snaked_Map"
GRID_WIDTH = 22   # tiles along X
GRID_HEIGHT = 40  # tiles along Y

# Layers stacked along Z. Layer 0 is the floor; layers 1..3 hold obstacles.
NUM_LAYERS = 4       # 1 floor + 3 obstacle layers
LAYER_HEIGHT = 1.0   # Z distance between layers (1 unit == 1 tile)


# ---------------------------------------------------------------------------
# Material helpers
# ---------------------------------------------------------------------------

def _get_material(name, color):
    """Return a material with the given name, creating it if needed."""
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = False
    mat.diffuse_color = (color[0], color[1], color[2], 1.0)
    return mat


# ---------------------------------------------------------------------------
# Collection / cleanup helpers
# ---------------------------------------------------------------------------

def get_map_collection():
    """Return the dedicated map collection, creating and linking it if needed."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        coll = bpy.data.collections.new(COLLECTION_NAME)
        bpy.context.scene.collection.children.link(coll)
    return coll


def clear_map():
    """Remove all previously generated objects (and their data) from the map."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        return

    for obj in list(coll.objects):
        mesh = obj.data if obj.type == 'MESH' else None
        bpy.data.objects.remove(obj, do_unlink=True)
        if mesh is not None and mesh.users == 0:
            bpy.data.meshes.remove(mesh)


def _link_to_map(obj):
    """Unlink an object from any other collection and place it in the map collection."""
    coll = get_map_collection()
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    coll.objects.link(obj)


# ---------------------------------------------------------------------------
# Geometry helper
# ---------------------------------------------------------------------------

class _GuideMeshBuilder:
    """Accumulates axis-aligned boxes and emits them all as ONE mesh object.

    The grid used to be one object -- with its own mesh datablock, created via
    a bpy.ops call -- per line segment, which meant hundreds of objects and a
    slow rebuild. Boxes added here become faces of a single shared mesh
    instead; colours are kept via one material slot per (name, colour) and
    per-face material indices.
    """

    # Standard cube faces over the 8 corner verts emitted by add_box.
    _FACES = (
        (0, 3, 2, 1), (4, 5, 6, 7),   # bottom, top
        (0, 1, 5, 4), (1, 2, 6, 5),   # -Y, +X
        (2, 3, 7, 6), (3, 0, 4, 7),   # +Y, -X
    )

    def __init__(self, name):
        self.name = name
        self.verts = []
        self.faces = []
        self.face_mats = []
        self.mats = []           # (mat_name, color) in material-slot order
        self._slot_by_name = {}

    def _mat_slot(self, name, color):
        slot = self._slot_by_name.get(name)
        if slot is None:
            slot = len(self.mats)
            self._slot_by_name[name] = slot
            self.mats.append((name, color))
        return slot

    def add_box(self, location, size, mat_name, color):
        """Append a box with explicit per-axis dimensions, centred on location."""
        cx, cy, cz = location
        hx, hy, hz = size[0] / 2.0, size[1] / 2.0, size[2] / 2.0
        base = len(self.verts)
        self.verts.extend((
            (cx - hx, cy - hy, cz - hz), (cx + hx, cy - hy, cz - hz),
            (cx + hx, cy + hy, cz - hz), (cx - hx, cy + hy, cz - hz),
            (cx - hx, cy - hy, cz + hz), (cx + hx, cy - hy, cz + hz),
            (cx + hx, cy + hy, cz + hz), (cx - hx, cy + hy, cz + hz),
        ))
        slot = self._mat_slot(mat_name, color)
        for f in self._FACES:
            self.faces.append((base + f[0], base + f[1],
                               base + f[2], base + f[3]))
            self.face_mats.append(slot)

    def build(self):
        """Create and return the merged mesh object (not linked anywhere yet)."""
        mesh = bpy.data.meshes.new(self.name)
        mesh.from_pydata(self.verts, [], self.faces)
        for name, color in self.mats:
            mesh.materials.append(_get_material(name, color))
        mesh.polygons.foreach_set("material_index", self.face_mats)
        mesh.update()
        return bpy.data.objects.new(self.name, mesh)


# ---------------------------------------------------------------------------
# Visible grid
# ---------------------------------------------------------------------------

def _create_grid_layer(builder, width, height, layer, z):
    """Add a single flat width x height grid at height z to the guide builder."""
    line_thickness = 0.02

    # The floor layer is brighter; obstacle layers are dimmer.
    if layer == 0:
        mat_name, color = "Snaked_GridFloor", (0.35, 0.35, 0.35)
    else:
        mat_name, color = "Snaked_GridLayer", (0.2, 0.2, 0.2)

    # Grid spans from -0.5 to N-0.5 on each axis so every integer tile sits in a cell.
    x_lo, x_hi = 0.5, width + 0.5
    y_lo, y_hi = 0.5, height + 0.5
    x_span = x_hi - x_lo
    y_span = y_hi - y_lo
    x_center = (x_lo + x_hi) / 2.0
    y_center = (y_lo + y_hi) / 2.0

    # Lines parallel to Y (varying X position).
    for i in range(width + 1):
        builder.add_box((x_lo + i, y_center, z),
                        (line_thickness, y_span, line_thickness),
                        mat_name, color)

    # Lines parallel to X (varying Y position).
    for j in range(height + 1):
        builder.add_box((x_center, y_lo + j, z),
                        (x_span, line_thickness, line_thickness),
                        mat_name, color)


def create_grid(width=GRID_WIDTH, height=GRID_HEIGHT, num_layers=NUM_LAYERS):
    """Create a stack of width x height grids, one per layer along Z.

    Layer 0 (z=0) is the floor; layers 1..num_layers-1 are obstacle layers
    spaced LAYER_HEIGHT apart. Tiles are centered on integer coordinates
    (0..width-1, 0..height-1) at each layer. Each layer's lines are merged
    into ONE mesh object (Snaked_Grid_L<n>) so it can still be hidden per
    layer without flooding the scene with per-line objects.
    """
    for layer in range(num_layers):
        z = layer * LAYER_HEIGHT
        builder = _GuideMeshBuilder("Snaked_Grid_L%d" % layer)
        _create_grid_layer(builder, width, height, layer, z)
        _link_to_map(builder.build())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def rebuild():
    """Clear any previous generation and rebuild the grid."""
    clear_map()
    get_map_collection()
    create_grid()
    print("[Snaked] Grid rebuilt: %dx%d x %d layers (1 floor + %d obstacle)." %
          (GRID_WIDTH, GRID_HEIGHT, NUM_LAYERS, NUM_LAYERS - 1))


if __name__ == "__main__":
    rebuild()
