"""
snaked_map_builder.py

A simple grid for the game "Snaked".

Conventions
-----------
- 1 Blender unit == 1 tile.
- X and Y are the grid directions.
- Z is height.
- Everything generated by this script is placed under a single
  collection ("Snaked_Map") so it can be wiped and rebuilt cleanly.

Run this from Blender's Text Editor (Alt+P) or via the command line:
    blender --python snaked_map_builder.py
"""

import os
import sys

import bpy


def _ensure_repo_on_path():
    """Put this repo's folder on sys.path so `import snaked_common` works no
    matter how the script is run (module import, blender --python, or the
    Text Editor's Alt+P on a saved file)."""
    dirs = []
    try:
        dirs.append(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        pass
    try:
        dirs.extend(
            os.path.dirname(os.path.abspath(bpy.path.abspath(t.filepath)))
            for t in bpy.data.texts if t.filepath)
        if bpy.data.filepath:
            dirs.append(os.path.dirname(bpy.data.filepath))
    except Exception:
        pass
    dirs.append(os.getcwd())
    for d in dirs:
        if os.path.isfile(os.path.join(d, "snaked_common.py")):
            if d not in sys.path:
                sys.path.insert(0, d)
            return


_ensure_repo_on_path()

import snaked_common as sc

# ---------------------------------------------------------------------------
# Configuration  (grid dimensions live in snaked_common -- shared with the
# tools panel so the two can never drift apart)
# ---------------------------------------------------------------------------

COLLECTION_NAME = "Snaked_Map"
GRID_WIDTH = sc.GRID_WIDTH     # tiles along X
GRID_HEIGHT = sc.GRID_HEIGHT   # tiles along Y

# Layers stacked along Z. Layer 0 is the floor; layers 1..3 hold obstacles.
NUM_LAYERS = sc.NUM_LAYERS       # 1 floor + 3 obstacle layers
LAYER_HEIGHT = sc.LAYER_HEIGHT   # Z distance between layers (1 unit == 1 tile)


# ---------------------------------------------------------------------------
# Collection / cleanup helpers
# ---------------------------------------------------------------------------

def get_map_collection():
    """Return the dedicated map collection, creating and linking it if needed."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        coll = bpy.data.collections.new(COLLECTION_NAME)
        bpy.context.scene.collection.children.link(coll)
    return coll


def clear_map():
    """Remove all previously generated objects (and their data) from the map."""
    coll = bpy.data.collections.get(COLLECTION_NAME)
    if coll is None:
        return

    for obj in list(coll.objects):
        sc.remove_object_with_orphan_data(obj)


def _link_to_map(obj):
    """Unlink an object from any other collection and place it in the map collection."""
    sc.link_to_collection(obj, get_map_collection())


# ---------------------------------------------------------------------------
# Geometry helper (shared: see snaked_common.GuideMeshBuilder)
# ---------------------------------------------------------------------------

_GuideMeshBuilder = sc.GuideMeshBuilder


# ---------------------------------------------------------------------------
# Visible grid
# ---------------------------------------------------------------------------

def _create_grid_layer(builder, width, height, layer, z):
    """Add a single flat width x height grid at height z to the guide builder."""
    line_thickness = 0.02

    # The floor layer is brighter; obstacle layers are dimmer.
    if layer == 0:
        mat_name, color = "Snaked_GridFloor", (0.35, 0.35, 0.35)
    else:
        mat_name, color = "Snaked_GridLayer", (0.2, 0.2, 0.2)

    # Grid spans from -0.5 to N-0.5 on each axis so every integer tile sits in a cell.
    x_lo, x_hi = 0.5, width + 0.5
    y_lo, y_hi = 0.5, height + 0.5
    x_span = x_hi - x_lo
    y_span = y_hi - y_lo
    x_center = (x_lo + x_hi) / 2.0
    y_center = (y_lo + y_hi) / 2.0

    # Lines parallel to Y (varying X position).
    for i in range(width + 1):
        builder.add_box((x_lo + i, y_center, z),
                        (line_thickness, y_span, line_thickness),
                        mat_name, color)

    # Lines parallel to X (varying Y position).
    for j in range(height + 1):
        builder.add_box((x_center, y_lo + j, z),
                        (x_span, line_thickness, line_thickness),
                        mat_name, color)


def create_grid(width=GRID_WIDTH, height=GRID_HEIGHT, num_layers=NUM_LAYERS):
    """Create a stack of width x height grids, one per layer along Z.

    Layer 0 (z=0) is the floor; layers 1..num_layers-1 are obstacle layers
    spaced LAYER_HEIGHT apart. Tiles are centered on integer coordinates
    (0..width-1, 0..height-1) at each layer. Each layer's lines are merged
    into ONE mesh object (Snaked_Grid_L<n>) so it can still be hidden per
    layer without flooding the scene with per-line objects.
    """
    for layer in range(num_layers):
        z = layer * LAYER_HEIGHT
        builder = _GuideMeshBuilder("Snaked_Grid_L%d" % layer)
        _create_grid_layer(builder, width, height, layer, z)
        _link_to_map(builder.build())


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def rebuild():
    """Clear any previous generation and rebuild the grid."""
    clear_map()
    get_map_collection()
    create_grid()
    print("[Snaked] Grid rebuilt: %dx%d x %d layers (1 floor + %d obstacle)." %
          (GRID_WIDTH, GRID_HEIGHT, NUM_LAYERS, NUM_LAYERS - 1))


if __name__ == "__main__":
    rebuild()
